version: "3.9"

services:

  # Defines build for Flask app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    # A volume basically mounts your source folder in the Docker
    # container so you don't have to restart the whole container
    # on every change
    volumes:
      - ./api:/app:cached

  # Defines build for React app
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app:cached
      - /app/node_modules
    links:
      - api